//@version=6
strategy("SMAs Crossovers Strategy /5m", overlay=true)

//_________________________________________________________________________________________________________________________| conditions
buySignal =     ta.crossover(ta.sma(close, 100), ta.sma(close, 200))
if (buySignal)
    strategy.entry("Buy ↑", strategy.long)

sellSignal =    ta.crossunder(ta.sma(close, 100), ta.sma(close, 200))
if (sellSignal)
    strategy.entry("Sell ↓", strategy.short)

//_________________________________________________________________________________________________________________________| convert
pointsConverter(money) =>
    strategy.position_size != 0 ? (money / syminfo.pointvalue / math.abs(strategy.position_size)) / syminfo.mintick : na

tpInPoints  = pointsConverter(input(1500, title="Target"))
slInPoints  = pointsConverter(input(1500, title="Stop"))
strategy.exit("Exit Trade", profit=tpInPoints, loss=slInPoints)

pointsToPriceLevel(pp) =>
    na(pp) ? na : strategy.position_avg_price + pp * math.sign(strategy.position_size) * syminfo.mintick

//_________________________________________________________________________________________________________________________| plotting
plotTarget  = plot(pointsToPriceLevel(tpInPoints),  style=plot.style_linebr, color=color.rgb(80, 255, 0, 50),       title="Profit")
plotStop    = plot(pointsToPriceLevel(-slInPoints), style=plot.style_linebr, color=color.rgb(255, 0, 0, 50),        title="Stop")
plotEntry   = plot(strategy.position_avg_price,     style=plot.style_linebr, color=color.rgb(0, 0, 0, 50),          title="Entry")

fill(plotTarget, plotEntry, color=color.rgb(0, 0, 0, 95))
fill(plotEntry, plotStop,   color=color.rgb(0, 0, 0, 95))